### ISSUE TITLE
ReferenceError: e is not defined

### ISSUE THREAD

**Issue by munjalpatel** [lukevanhorn/express-session-documentdb#1]
Hello,

I am getting this error when I try to load my app in browser.
I followed all exact steps as suggested in README.

It does create database and collection just fine though.

Here is how my app is structured:

**server.js**

```
var env = process.env.NODE_ENV = process.env.NODE_ENV || 'development';

var express = require('express'),
    config  = require('./server/config/settings')[env];

var app = express();

config.rootPath = __dirname;

require('./server/config/express')(app, config);

app.get('*', function(req, res) {
   res.render('index');
});

app.listen(4000, function() {
   console.log('Listening on port 4000...');
});
```

**/server/config/express.js**

```
var express = require('express'),
    path = require('path'),
    logger = require('morgan'),
    session = require('express-session'),
    cookieParser = require('cookie-parser'),
    DocDbSessionStore = require('express-session-documentdb');

module.exports = function(app, config) {
  app.use(logger('dev'));

  app.use(cookieParser(config.secret));

  app.use(session({
    name: 'reportiq.sid',
    secret: config.secret,
    resave: true,
    saveUninitialized: true,
    store: new DocDbSessionStore({
      host: config.docDb.host,
      authKey: config.docDb.key,
      databaseId: 'MyAppSessionStore'
    })
  }));

  app.use(function(req, res, next) {
    if(req.session && req.session.isAuthenticated) return next();

    console.log('Not authenticated...');

    req.session.regenerate(function(err) {
      if(!err) {
        console.log('Redirecting...');
      }

      console.error('Cannot initialize session. Error: ' + err);
    });
  });

  app.use(express.static(path.join(config.rootPath, 'client')));
  app.set('views', config.rootPath + '/server/views');
  app.set('view engine', 'ejs');
};
```

**/server/config/settings.js**

```
module.exports = {
  development: {
    secret: 'MySecret',
    docDb: {
      host: 'https://myapp.documents.azure.com:443/',
      key: 'MyPrimaryKey'
    }
  },

  production: {
    secret: process.env.SECRET,
    docDb: {
      host: process.env.DOC_DB_HOST,
      key: process.env.DOC_DB_KEY
    }
  }
};
```

---

```
/app/node_modules/express-session-documentdb/lib/express-session-documentdb.js:91
                    return callback(e);
                                    ^
ReferenceError: e is not defined
    at /app/node_modules/express-session-documentdb/lib/express-session-documentdb.js:91:37
    at Base.defineClass._toArrayImplementation (/app/node_modules/express-session-   documentdb/node_modules/documentdb/queryIterator.js:159:17)
    at /app/node_modules/express-session-documentdb/node_modules/documentdb/queryIterator.js:155:26
    at /app/node_modules/express-session-documentdb/node_modules/documentdb/queryIterator.js:201:17
    at successCallback (/app/node_modules/express-session-documentdb/node_modules/documentdb/documentclient.js:1491:17)
    at IncomingMessage.<anonymous> (/app/node_modules/express-session-documentdb/node_modules/documentdb/request.js:62:20)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by lukevanhorn** [comment]
Hi, thanks for posting.  I published a fix to npm just now.  version 1.2.  

Thanks!
